config/routes.rb
Rails.application.routes.draw do
  # get 'properties/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resource :properties do
    collection do
      post :search
    end
  end

  root "properties#index"

  # resources :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  validates :address, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
    # if params[:query].present?
    #   @properties = Property.where("country LIKE ? OR city LIKE ?","%#{params[:query]}%", "%#{params[:query]}%")
    # else
    #   @properties = Property.all
    # end
      # Not too clean but it works!
    # if turbo_frame_request?
    #   render partial: "show", locals: { properties: @properties }
    # else
    #   render :index
    # end
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    if @property.save
      respond_to do |format|
        # flash[:success] = "Object successfully created"
        format.html{redirect_to properties_url, notice: "Object successfully created"}
        format.turbo_stream {flash.now[:notice] = "Property successfully created"}
      end
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
      redirect_to properties_url
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def destroy 
    @property = Property.find(params[:id])
    if @property.destroy
      redirect_to properties_url
    else
      flash[:error] = "Something went wrong"
    end
  end

  def search
    if params[:query].present?
      @properties = Property.where("country LIKE ? OR city LIKE ?","%#{params[:query]}%", "%#{params[:query]}%")
    else
      @properties = []
    end
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: turbo_stream.update("search_result", partial:"properties/search_results", local: {property: @property})
      end
    end
  end
  
  private
  
    def property_params
      params.require(:property).permit(:address, :street, :city, :country)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurdTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with model: @property do |form| %>
<div>
  <%= form.label :address %><br>
  <%= form.text_area :address %>
</div>

<div>
  <%= form.label :street %><br>
  <%= form.text_area :street %>
</div>

<div>
  <%= form.label :city %><br>
  <%= form.text_field :city %>
</div>
<div>
  <%= form.label :country %><br>
  <%= form.text_field :country %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/properties/_property.html.erb
<%= property.address %>, <%= property.street %>, <%= property.city %>, <%= property.country %>
<%= link_to "Edit", edit_property_path(property) %>
<%= link_to "Delete", property_path(property), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/properties/_search_form.html.erb
<%= form_with url: search_properties_path, method: :post do |form|%>
<%= form.search_field :query, oninput: "this.form.requestSubmit()" %>
<% end%>

<div id="search_result">Search by City or Country</div>

app/views/properties/_search_results.html.erb
<% @properties.each do |property| %>
<br>
<%= property.address %>, <%= property.street %>, <%= property.city %>, <%= property.country %>
<%end%>

app/views/properties/_show.html.erb
<%= turbo_frame_tag dom_id(property) do %>
<%= property.address %>, <%= property.street %>, <%= property.city %>, <%= property.country %>
<%= link_to "Edit", edit_properties_path(property) %>
<%= link_to "Delete", properties_path(property), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %><br>
<% end %>

app/views/properties/create.turbo_stream.erb
<%= turbo_stream.prepend"properties", partial: "properties/show", locals:{property: @property} %>
<%= turbo_stream.update Property.new, ""%>

app/views/properties/edit.html.erb
<h1>Edit Property</h1>
<%= turbo_frame_tag @property do %>
<%= render "form", property: @property %>
<% end %>

app/views/properties/index.html.erb
<h1>List of all Properties</h1>
<!-- <p>Find me in app/views/properties/index.html.erb</p> -->
<!-- <%= form_with(url: properties_path, method: :get, data: { turbo_frame: "properties", turbo_action: "advance"}) do |form| %>
<%= form.label :query, "Search by Country or City" %>
<%= form.search_field :query, oninput: "this.form.requestSubmit()" %> -->
<!-- <%= form.submit "Search" %> -->
<!-- <%end%> -->
<%= render "search_form" %>
<!-- Pratial file cut from here -->
<ul>
  <% @properties.each do |property| %>

  <li>
    <%= turbo_frame_tag Property.new %>
    <%= turbo_frame_tag  "properties" do %>
    <%= render "show", property: property%>
    <% end %>
  </li>

  <%end%>

</ul>

<!-- <%= turbo_frame_tag @properties do %> -->
<%= link_to "New Property", new_properties_path, data:{turbo_frame: dom_id(Property.new)} %>
<!-- <%end%> -->

app/views/properties/new.html.erb
<h1>New Property</h1>
<%= turbo_frame_tag @property do %>
<%= render "form", property: @property %>
<%end%>